### ISSUE TITLE
should router support non string values for params?

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-router#34]
See discussion at https://github.com/christianalfoni/cerebral-router/pull/32#discussion_r41154274

Use case 1:
```
// /popup/show/:state, 'popupTriggered'
controller.signals.popupTriggered({
  state: this.props.popupVisible
})
```

*Solution A.* Allow to pass boolean.

Pros
* Intuitive
* No need to change signal call

Cons
* When triggered from url, `state` would passed as string but not boolean
* Have to change actions to check `state`'s type and convert it
* Developer wouldn't know about previous point (string would pass to input silently if developer is not enabled type checkings)

*Solution B.* Support only string. (not boolean, numbers undefined, etc)
```
controller.signals.popupTriggered({
  state: this.props.popupVisible.toString()
})
```

Pros
* `state` param would always be string no matter it come from signal call or url trigger.
* Developer would be warned and instructed what to do
* Easy to change signal call as well as action using this param

Cons
* Unintuitive
* Have to change signal call as well as action using this param if it used boolean previously

**Comment by christianalfoni** [comment]
I suggest we use `JSON.parse` with try/catch on the value. It will convert it correctly with numbers and booleans, and if it throws it means it should just be a string. This is kind of interesting as we would allow for url params to be objects... would be cool to explore?

**Comment by Guria** [comment]
I suggest that passing objects in base64 would be more safer and reliably:
```js
ew0KICAianNvbiI6IHRydWUsDQogICJzb21lLXN0cmluZyI6ICJ2YWx1ZSIsDQogICJ1bHRpbWF0ZSBhbnN3ZXIgdG8gbGlmZSwgdGhlIHVuaXZlcnNlLCBhbmQgZXZlcnl0aGluZyI6IDQyDQp9
```

**Comment by Guria** [comment]
Agreed. I'll try to experiment with `JSON.stringify` / `JSON.parse`

**Comment by Guria** [comment]
Moving to `path-to-regexp` partially resolves this issue as well. But still have to parse from string.

**Comment by Guria** [comment]
now it solved since using `urlon`
